require('./db/mongoose')
const express=require('express')
const app=express()
const kishanRouter=require('./router/kishan')
const signupRouter=require('./router/signup')
 const loginRouter=require('./router/login')
const updateRouter=require('./router/update')
const ejs=require('ejs')
app.set('view engine','ejs')
app.use(kishanRouter)
app.use(signupRouter)
 app.use(loginRouter)
app.use(updateRouter)
app.listen('3000',()=>{
    console.log('it is connected at 3000')
})
