require('db/mongoose')
const express = require('express')
const app = express()
const kishanRouter = require('router/kishan')
const signupRouter = require('router/signup')
const loginRouter = require('router/login')
const updateRouter = require('router/update')
const productsRouter = require('router/products')
// const ejs = require('ejs')

app.set('view engine', 'ejs')
app.use(kishanRouter)
app.use(signupRouter)
app.use(loginRouter)
app.use(updateRouter)
app.use(productsRouter)
app.use(express.static(__dirname + '/public'));
app.listen('3000', () => {
    console.log('Server running at port 3000')
})